startupProbe:
  httpGet:
    path: /healthz
    port: liveness-port
  failureThreshold: 30
  periodSeconds: 10
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: mylivenessprobe
spec:
  containers:
  - name: liveness
    image: ubuntu
    command: ["/bin/sh","-c","touch /tmp/healthy; sleep 1000"]
    startupProbe:
      exec:
        command: ["/bin/sh","-c","cat /etc/foo"]
      periodSeconds: 2
      failureThreshold: 2
